---
- hosts: all
  sudo: yes
  gather_facts: true # roles use ansible_os_family
  vars_files:
    - vars/main.yml  
  roles:
    - { role: java }
    - { role: tomcat }
    - { role: postgresql }
    - { role: xnat }
      

