---
#ftp server has all downloads available but get_url module not working reliably with ftp (June 2017)
#ftp://ftp.nrg.wustl.edu/pub/xnat/

#use for remote targets
#- name: "Download XNAT-{{ xnat_version }} snapshot .war directly to Tomcat webapps folder"
#  get_url: 
#    url=https://bitbucket.org/xnatdev/xnat-web/downloads/{{ xnat.tarball }} 
#    dest=/var/lib/tomcat{{ tomcat_version }}/webapps/ROOT.war
#    force=no 
#    timeout=30
#    tmp_dest=/tmp

#use for local targets e.g. vagrant boxes
- name: "Copy over local {{ xnat.tarball }} to target Tomcat webapps folder (Debian.)"
  copy:
    src=~/Downloads/{{ xnat.tarball }}
    dest=/var/lib/tomcat{{ tomcat_version }}/webapps/ROOT.war
  when: ansible_os_family == 'Debian'

- name: "Copy over local {{ xnat.tarball }} to target Tomcat webapps folder (RedHat.)"
  copy:
    src=~/Downloads/{{ xnat.tarball }}
    dest=/usr/share/tomcat{{ tomcat_version }}/webapps/ROOT.war
  when: ansible_os_family == 'RedHat'

- name: "Add system user {{ tomcat.user }}"
  user: name={{ tomcat.user }} shell=/bin/bash # XXX: restrict shell?

# unreliable
#- name: "Download XNAT directly from GitHub"
#  get_url: url=http://github.com/boxerab/xnat/archive/master.tar.gz dest=/tmp/{{ xnat.tarball }} force=no

# only needed for github download
#- name: "Symlink for Github xnat-master"
#  file: src={{ xdat.app_src }}-master dest={{ xdat.app_src }} owner={{ tomcat }} group={{ tomcat }} state=link

- name: "Setup XNAT data directories"
  file: path="{{ xnat_root }}/{{ item }}" group={{ tomcat.group }} owner={{ tomcat.user }} state=directory
  with_items:
      - build
      - archive
      - prearchive
      - cache
      - ftp
      - pipeline
      - home 
      - home/config
      - home/logs
      - home/plugin
      - home/work

- name: "Copy xnat-config.properties"
  template: src=xnat-config.properties.j2 dest={{ xnat_home }}/config owner={{ tomcat.user }} group={{ tomcat.group }} mode=0644 force=yes

- name: "Adjust XNAT deployment permissions"
  file: path={{ xnat_root }} group={{ tomcat.group }} owner={{ tomcat.user }} recurse=yes

- name: "Create XNAT PostgreSQL user"
  postgresql_user: name={{ xnat.pg_user }} password={{ xnat.pg_password }}

- name: "Create XNAT PostgreSQL db"
  postgresql_db: name={{ xnat.pg_database }} owner={{ xnat.pg_user }}
  notify: restart tomcat