---
#- name: "Download XNAT tarball"
#  get_url: url=ftp://ftp.nrg.wustl.edu/pub/xnat/{{ xnat_tarball }} dest=/tmp/{{ xnat_tarball }} force=no 

- name: "Download XNAT directly from GitHub"
  get_url: url=http://github.com/boxerab/xnat/archive/master.tar.gz dest=/tmp/{{ xnat_tarball }} force=no

- name: "Unpack XNAT"
  unarchive: src=/tmp/{{ xnat_tarball }} dest=/usr/local copy=no

- name: "Symlink for Github xnat-master"
  file: src={{ xdat.app_src }}-master dest={{ xdat.app_src }} owner={{ tomcat }} group={{ tomcat }} state=link

- name: "Copy build.properties"
  template: src=build.properties.j2 dest={{ xdat.app_src }}/build.properties

- name: "Copy default tomcat6 debian file. Username change, as advised by XNAT docs"
  template: src=tomcat6.j2 dest=/etc/default/tomcat6
  when: ansible_os_family == 'Debian'

- name: "Setup XNAT data directories structure (LFH compliant)"
  file: path={{ item }} group={{ tomcat }} owner={{ tomcat }} state=directory
  with_items:
      - "{{ xdat.archive_location }}"
      - "{{ xdat.prearchive_location }}"
      - "{{ xdat.cache_location }}"
      - "{{ xdat.ftp_location }}"
      - "{{ xdat.build_location }}"
      - "{{ xdat.modules_location }}"
  #    - "{{ xdat.pipeline_location }}" # XXX: requires special handling

- name: "Copy setenv.sh with JAVA_HOME for tomcat"
  template: src=setenv.sh dest={{ xdat.app_src }}/bin/setenv.sh 

# XXX: Ugly fix to not bail out on setup, to be fixed upstream:
# https://groups.google.com/forum/#!topic/xnat_discussion/acPuE4__2YM
- name: "Patch maven to ignore deployment issues"
  lineinfile: >
        dest={{ xdat.app_src }}/maven.xml
        regexp='<java classname="GenerateAllCreateFiles" maxmemory="1024m" fork="true" failonerror="true">'
        line='<java classname="GenerateAllCreateFiles" maxmemory="1024m" fork="true" failonerror="false">'

- name: "Setup XNAT database"
  include: postgresql.yml

- name: "Run setup.sh"
  shell: chdir={{ xdat.app_src }} . ./bin/setenv.sh && ./bin/setup.sh

- name: "Fill XNAT postgresql database with generated .sql from setup.sh"
  command: psql -f {{ xdat.app_src }}/deployments/{{ xdat.project_name }}/sql/{{ xdat.project_name }}.sql -U {{ tomcat }} {{ dbname }}

- name: "Adjust default XNAT security settings"
  shell: chdir={{ xdat.app_src }}/deployments/{{ xdat.project_name }} . {{ xdat.app_src }}/bin/setenv.sh {{ item }}
  with_items:
      - "{{ xdat.app_src }}/bin/StoreXML -project {{ xdat.project_name }} -l security/security.xml -allowDataDeletion true"
      - "{{ xdat.app_src }}/bin/StoreXML -dir ./work/field_groups -u admin -p admin -allowDataDeletion true"

- name: "Deploy XNAT to tomcat"
  shell: chdir={{ xdat.app_src }} . ./bin/setenv.sh && ./bin/update.sh -Ddeploy=true

- name: "Adjust XNAT/tomcat permissions post-deployment and start tomcat"
  file: path={{ xdat.maven_appserver_home }} group={{ tomcat }} owner={{ tomcat }} state=directory recurse=yes
  notify: restart tomcat
