---
#- name: "Download XNAT tarball"
#  get_url: url=ftp://ftp.nrg.wustl.edu/pub/xnat/xnat-1.6.3.tar.gz dest=/tmp

#- name: "Unpack XNAT"
#  unarchive: src=/tmp/xnat-1.6.3.tar.gz dest=/usr/local copy=no

- name: "Copy build.properties"
  template: src=build.properties.j2 dest=/usr/local/xnat/build.properties

#include: postgresql.yml
