---
- name: "Install OpenJDK"
  apt: pkg={{ java_packages }}
  when: ansible_os_family == 'Debian'

- name: "Setup XNAT database, username and password"
  include: postgresql.yml

- name: "Download XNAT tarball"
  get_url: url=ftp://ftp.nrg.wustl.edu/pub/xnat/{{ xnat_tarball }} dest=/tmp/{{ xnat_tarball }} force=no 

- name: "Unpack XNAT"
  unarchive: src=/tmp/{{ xnat_tarball }} dest=/usr/local copy=no

- name: "Copy build.properties"
  template: src=build.properties.j2 dest=/usr/local/xnat/build.properties

- name: "Copy default tomcat6 debian file. Username change, as advised by XNAT docs"
  template: src=tomcat6.j2 dest=/etc/default/tomcat6
  when: ansible_os_family == 'Debian'

- name: "Setup XNAT data directories structure"
  file: path={{ item }} group={{ tomcat }} owner={{ tomcat }} state=directory
  with_items:
      - "{{ xdat.archive_location }}"
      - "{{ xdat.prearchive_location }}"
      - "{{ xdat.cache_location }}"
      - "{{ xdat.ftp_location }}"
      - "{{ xdat.build_location }}"
      - "{{ xdat.modules_location }}"
  #    - "{{ xdat.pipeline_location }}" # XXX: requires special handling

- name: "Set JAVA_HOME for tomcat"
  template: src=setenv.sh dest=/usr/local/xnat/bin/setenv.sh 

# XXX: Ugly fix to not bail out on setup, to be fixed upstream:
# https://groups.google.com/forum/#!topic/xnat_discussion/acPuE4__2YM
- name: "Patch maven to ignore deployment issues"
  lineinfile: >
        dest=/usr/local/xnat/maven.xml
        regexp='<java classname="GenerateAllCreateFiles" maxmemory="1024m" fork="true" failonerror="true">'
        line='<java classname="GenerateAllCreateFiles" maxmemory="1024m" fork="true" failonerror="false">'

- name: "Run setup.sh"
  shell: chdir=/usr/local/xnat . ./bin/setenv.sh && ./bin/setup.sh -Ddeploy=True
