---
#ftp server has all downloads available but get_url module not working reliably with ftp (June 2017)
#ftp://ftp.nrg.wustl.edu/pub/xnat/

#use for remote targets
#- name: "Download XNAT-{{ xnat_version }} snapshot .war directly to Tomcat webapps folder"
#  get_url: 
#    url=https://bitbucket.org/xnatdev/xnat-web/downloads/{{ xnat_tarball }} 
#    dest=/var/lib/tomcat{{ tomcat_version }}/webapps/ROOT.war
#    force=no 
#    timeout=30
#    tmp_dest=/tmp

#use for local targets e.g. vagrant boxes
- name: "Copy over local {{ xnat_tarball }} to target Tomcat webapps folder (Debian.)"
  copy:
    src=~/Downloads/{{ xnat_tarball }}
    dest=/var/lib/tomcat{{ tomcat_version }}/webapps/ROOT.war
  when: ansible_os_family == 'Debian'

- name: "Copy over local {{ xnat_tarball }} to target Tomcat webapps folder (RedHat.)"
  copy:
    src=~/Downloads/{{ xnat_tarball }}
    dest=/usr/share/tomcat{{ tomcat_version }}/webapps/ROOT.war
  when: ansible_os_family == 'RedHat'

- name: "Add system user {{ tomcat }}"
  user: name={{ tomcat }} shell=/bin/bash # XXX: restrict shell?

# unreliable
#- name: "Download XNAT directly from GitHub"
#  get_url: url=http://github.com/boxerab/xnat/archive/master.tar.gz dest=/tmp/{{ xnat_tarball }} force=no

# only needed for github download
#- name: "Symlink for Github xnat-master"
#  file: src={{ xdat.app_src }}-master dest={{ xdat.app_src }} owner={{ tomcat }} group={{ tomcat }} state=link

- name: "Copy default tomcat{{ tomcat_version }} debian file. Username change, as advised by XNAT docs"
  template: src=tomcat.j2 dest=/etc/default/tomcat{{ tomcat_version }}
  when: ansible_os_family == 'Debian'

- name: "Setup XNAT data directories structure (LFH compliant)"
  file: path="{{ xnat_root }}/{{ item }}" group={{ tomcat }} owner={{ tomcat }} state=directory
  with_items:
      - build
      - archive
      - prearchive
      - cache
      - ftp
      - pipeline
      - home 
      - home/config
      - home/logs
      - home/plugin
      - home/work

- name: "Adjust XNAT deployment permissions"
  file: path={{ xnat_root }} group={{ tomcat }} owner={{ tomcat }} recurse=yes

- name: "Make sure the dependencies are installed"
  apt:
    pkg: "{{item}}"
    state: present
  with_items: ["python-psycopg2", "python-pycurl"]

- name: "Create XNAT PostgreSQL user"
  postgresql_user: name=xnat password=xnat

- name: "Create XNAT PostgreSQL db"
  postgresql_db: name=xnat owner=xnat

#- name: "Fill XNAT postgresql database with generated .sql from setup.sh"
#  command: su "{{ tomcat }}" -c "psql -f {{ xdat.app_src }}/deployments/{{ xdat.project_name }}/sql/{{ xdat.project_name }}.sql -U {{ dbuser }} {{ dbname }}"

#- name: "Adjust default XNAT security settings"
#  shell: chdir={{ xdat.app_src }}/deployments/{{ xdat.project_name }} . {{ xdat.app_src }}/bin/setenv.sh {{ item }}
#  with_items:
#      - "{{ xdat.app_src }}/bin/StoreXML -project {{ xdat.project_name }} -l security/security.xml -allowDataDeletion true"
#      - "{{ xdat.app_src }}/bin/StoreXML -dir ./work/field_groups -u admin -p admin -allowDataDeletion true"

#- name: "Adjust XNAT/tomcat permissions post-deployment and start tomcat"
#  file: path={{ xdat.maven_appserver_home }} group={{ tomcat }} owner={{ tomcat }} state=directory recurse=yes
#  notify: restart tomcat
